config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'users#index'
  delete '/users/sign_out', to: 'devise/sessions#destroy'
  # Defines the root path route ("/")
  resources :users, only: [:index, :show, :new, :create] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, :likes
    end
  end

  get "/users/:id", to: "users#show"
  get "/users/:user_id/posts", to: "posts#index"
  get "/users/:user_id/posts/new", to: "posts#new"
  get "/users/:user_id/posts/:id", to: "posts#show"
  post "/users/:user_id/posts/new", to: "posts#create"
  delete '/users/:user_id/posts/:id', to: 'posts#destroy'

    #API routes
    namespace :api do
      resources :users, only: [] do
        resources :posts, only: [:create, :index] do
          resources :comments, only: [:create, :index]
        end
      end
    end
end

app/views/partials/_comment_form.html.erb
 <%= bootstrap_form_with model: @comment, url: user_post_comments_path, method: :post, local: true do |f|%>

  <%= f.text_area :text %>
  <%= f.submit %>

<% end %>

app/views/partials/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Blog App</a>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
        <%= link_to 'Home', root_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
        <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= button_to 'Create Post', new_user_post_path, method: :get, class:"nav-link active" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/partials/_post_form.html.erb
 <%= bootstrap_form_with model: @post, url: user_posts_path, method: :post, local: true do |f|%>

  <%= f.text_field :title %>
  <%= f.text_area :text %>
  <%= f.submit %>

<% end %>

app/views/partials/_user_form.html.erb
<%= bootstrap_form_with model: @user, local: true do |f| %>

  <%= f.text_field :name %>
  <%= f.text_area :photo %>
  <%= f.text_area :bio %>
  <%= f.submit %>

<% end %>