config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'users#index'
  delete '/users/sign_out', to: 'devise/sessions#destroy'
  # Defines the root path route ("/")
  resources :users, only: [:index, :show, :new, :create] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, :likes
    end
  end

  get "/users/:id", to: "users#show"
  get "/users/:user_id/posts", to: "posts#index"
  get "/users/:user_id/posts/new", to: "posts#new"
  get "/users/:user_id/posts/:id", to: "posts#show"
  post "/users/:user_id/posts/new", to: "posts#create"
  delete '/users/:user_id/posts/:id', to: 'posts#destroy'

    #API routes
    namespace :api do
      resources :users, only: [] do
        resources :posts, only: [:create, :index] do
          resources :comments, only: [:create, :index]
        end
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments
  has_many :likes

  # Validations
  validates :name, presence: true, length: { maximum: 50 }, format: { with: /\A[a-zA-Z0-9]+\z/ }
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.includes(:posts)
  end

  def show
    @user = User.find(params[:id])
  end

  def new; end

  def create; end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/index.html.erb
<h1 class="mx-auto col-sm-8">Users List</h1>

<% @users.each do |user| %>
    <div class="card col-sm-8 mb-4 mx-auto">
        <div class="card-header d-flex">
         <img style="width:75px; height:80px" class="img-thumbnail" src="<%= user.photo %>" />
            <%= link_to user.name, user_path(user) %>
        </div>
        <div class="card-body">
            <h5 class="card-title d-flex justify-content-end">POST COUNT:
            <%= user.posts.count %>
            </h5>
        </div>
    </div>
<% end %>

app/views/users/new.html.erb
<%= render '/partials/user_form' %>

app/views/users/show.html.erb
<div>
    <div class="card col-sm-6 mb-4 mx-auto">
        <div class="card-header">
            <div class="d-flex">
                <img style="width:135px; height:130px" class="d-flex justify-content-end" src="<%= @user.photo %>" />
                <h5 class="mx-5 pt-5"><%= @user.name %></h5>
            </div>
            <p class="card-title d-flex justify-content-end top-0">Post count:
                <%= @user.posts.count %>
            </p>
        </div>
        <div class="card-body">
            <h4 class="pb-4">Biography:</h4>
            <p>
                <%= @user.bio %>
            </p>
        </div>
    </div>

    <div>
      <h3 class="col-sm-6 mx-auto">Posts</h3>
        <% @user.recent_posts.each do |post| %>
        <div class="card col-sm-6 mb-4 mx-auto">
            <div class="card-header">
            <p>Post number: <%= post.id %></p>
            <h5><%= link_to post.title, user_post_path(@user, post) %></h5>
            </div>
            <div class="card-body">
                <p>
                <%= post.text %>
                </p>
            </div>
            <div class="d-flex justify-content-end">
                <p>View Comments:
                    <%= post.comments_counter  %>
                </p>
                <p class="px-5">Likes:
                    <%= post.likes_counter %>
                </p>
            </div>
        </div>
        <% end %>
    </div>

    <div class="d-grid gap-2">
        <%= link_to 'See All Posts', user_posts_path(@user), class: "mx-auto btn btn-primary mb-5 btn-lg" %>
    </div>
</div>