config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'users#index'
  delete '/users/sign_out', to: 'devise/sessions#destroy'
  # Defines the root path route ("/")
  resources :users, only: [:index, :show, :new, :create] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, :likes
    end
  end

  get "/users/:id", to: "users#show"
  get "/users/:user_id/posts", to: "posts#index"
  get "/users/:user_id/posts/new", to: "posts#new"
  get "/users/:user_id/posts/:id", to: "posts#show"
  post "/users/:user_id/posts/new", to: "posts#create"
  delete '/users/:user_id/posts/:id', to: 'posts#destroy'

    #API routes
    namespace :api do
      resources :users, only: [] do
        resources :posts, only: [:create, :index] do
          resources :comments, only: [:create, :index]
        end
      end
    end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :comments
  has_many :likes

  # Validations
  validates :title, presence: true, length: { maximum: 250 }, format: { with: /\A[a-zA-Z0-9 ]+\z/ }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: false }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  def update_user_posts_count
    author.posts_counter = author.posts.count
    save
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < Api::ApplicationController
  def index
    @posts = Post.where(author_id: params[:user_id])
    if @posts
      render json: @posts
    else
      render json: { status: 'Error', error: 'User has no posts' }
    end
  end

  def show
    @post = Post.where(id: params[:id])
    render json: @post
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments, :likes)
  end

  def show
    @user = current_user
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    @post.comments_counter = 0
    @post.likes_counter = 0
    if @post.save
      flash[:success] = 'Post created successfully'
      redirect_to user_posts_path(current_user)
    else
      flash[:error] = 'Error: Post could not be saved'
      render 'new'
    end
  end

  def destroy
    @user = current_user
    @post = Post.find(params[:id])
    authorize! :destroy, @post
    @user.posts_counter -= 1
    @post.destroy
    redirect_to user_posts_path(@user)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<div>
    <div class="card col-sm-8 mb-4 mx-auto">
        <div class="card-header d-flex">
          <img style="width:135px; height:130px" src="<%= @user.photo %>" />
          <h5 class="mx-5 mt-5"><%= @user.name %>
            <p class="position-absolute end-0 mx-4">POST COUNT:
            <%= @user.posts.count %>
            </p>
    </div>
        
    </div>

    <% @posts.each do |post, i| %>
    <% comments = post.recent_comments %>
    <div class="card col-sm-8 mb-4 mx-auto">
        <div class="card-header d-flex">
           <%= link_to post.title, user_post_path(@user, post)  %>
        </div>
        <div class="card-body">
            <p class="card-title d-flex justify-content-end">
            <%= post.text %>
            </p>
        </div>
        <div class="d-flex justify-content-end">
                 <p>
                    <%= button_to 'Delete Post', user_post_path(@user, post), method: :delete, class:"btn btn-danger mx-2"   %>
                </p>
                <p>Comments:
                    <%= post.comments.count  %>
                </p>
                <p class="px-5">Likes:
                    <%= post.likes.count %>
                </p>
        </div>
    </div>
    <div>
    <% comments.each do |comment| %>
        <div class="card mb-4 col-sm-4 mx-auto">
          <h4 class="card-title">
             <%= comment.author.name %>
          </h4>
          <p class="card-body">
             <%= comment.text %>
          </p>
          <p>
            <%= button_to 'Delete Comment', user_post_comment_path(@user, post, comment), method: :delete, class:"btn btn-danger mx-2"   %>
        </p>
        </div>
    <% end %>
    </div>
        <% end %>

    <div class="d-grid gap-2">
        <%= link_to 'Pagination', user_posts_path(@user), class: "mx-auto btn btn-primary mb-5 btn-lg" %>
    </div>
</div>

app/views/posts/new.html.erb
<%= render '/partials/post_form' %>

<% if flash[:success] %>
  <div class="notice"><%= flash[:success] %></div>
<% end %>

<% if flash[:error] %>
  <div class="notice"><%= flash[:error] %></div>
<% end %>

app/views/posts/show.html.erb
<div class="card">
    <h4>Post No: <%= @post.id  %></h4>
    <h4>Post by: <%= @post.author.name  %> Post Title: <%= @post.title %> </h4>
    <h4>Number of comments: <%= @comments.count  %></h4>
    <h4>Number of Likes: <%= @post.likes.count  %></h4>
    <p> <%= @post.text  %></p>
    
    <div>
      <%= link_to 'Add Comment', new_user_post_comment_path(@user, @post) %>
       <%= form_with model: Like.new, url: user_post_likes_path(@user, @post) do |form| %>
         <% form.submit :Like,  class:"btn btn-primary"%>
       <% end %>
    </div>

    <div class="card">
    <% comments = @post.recent_comments%>
     <% comments.each do |comment| %>
        <div class="card mb-4 col-sm-4 mx-auto">
          <h4 class="card-title">
             <%= comment.author.name %>
          </h4>
          <p class="card-body">
             <%= comment.text %>
          </p>
        </div>
    <% end %>
    </div>
</div>